remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: david-kyrat-uni-resources
description: "Repo used to host & quickly access resources, projects and other things Uni-related with GitHub pages"
show_downloads: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
